# Generated by Django 5.1.1 on 2024-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_rename_publicacion_libro_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
